export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_ERROR = "REGISTER_REQUEST_ERROR";
export const EMPLOYESS_LIST_REQUEST = "EMPLOYESS_LIST";
export const EMPLOYESS_LIST_REQUEST_SUCCESS = "EMP_REGISTER_REQUEST_SUCCESS";
export const EMPLOYESS_LIST_REQUEST_ERROR = "EMP_REGISTER_REQUEST_ERROR";
export const EMPLOYES_DELETE_REQUEST = "EMPLOYES_DELETE_REQUEST";
export const EMPLOYES_DELETE_REQUEST_SUCCESS =
  "EMPLOYES_DELETE_REQUEST_SUCCESS";
export const EMPLOYES_DELETE_REQUEST_ERROR = "EMPLOYES_DELETE_REQUEST_ERROR";
export const SETTINGS_INFO_REQUEST = "SETTINGS_INFO_REQUEST";
export const SETTINGS_INFO_REQUEST_SUCCESS = "SETTINGS_INFO_REQUEST_SUCCESS";
export const SETTINGS_INFO_REQUEST_ERROR = "SETTINGS_INFO_REQUEST_ERROR";
export const INVENTORY_LIST_REQUEST = "INVENTORY_LIST_REQUEST";
export const INVENTORY_LIST_SUCCESS = "INVENTORY_LIST_SUCCESS";
export const INVENTORY_LIST_ERROR = "INVENTORY_LIST_ERROR";
export const INVENTORY_DELETE_REQUEST = "INVENTORY_DELETE_REQUEST";
export const INVENTORY_DELETE_SUCCESS = "INVENTORY_DELETE_SUCCESS";
export const INVENTORY_DELETE_ERROR = "INVENTORY_DELETE_ERROR";
export const ACCOUNT_INFO_REQUEST = "ACCOUNT_INFO_REQUEST";
export const ACCOUNT_INFO_REQUEST_SUCCESS = "ACCOUNT_INFOR_REQUEST_SUCCESS";
export const ACCOUNT_INFO_REQUEST_ERROR = "ACCOUNT_INFOR_REQUEST_ERROR";
export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_REQUEST_SUCCESS = "DASHBOARD_REQUEST_SUCCESS";
export const DASHBOARD_REQUEST_ERROR = "DASHBOARD_REQUEST_ERROR";
export const GET_BUSINESS_HOUR_REQUEST = "GET_BUSINESS_HOUR_REQUEST";
export const GET_BUSINESS_HOUR_REQUEST_SUCCESS =
  "GET_BUSINESS_HOUR_REQUEST_SUCCESS";
export const GET_BUSINESS_HOUR_REQUEST_ERROR =
  "GET_BUSINESS_HOUR_REQUEST_ERROR";
export const ADD_VS_EDIT_BUSINESS_HOUR_REQUEST =
  "ADD_VS_EDIT_BUSINESS_HOUR_REQUEST";
export const ADD_VS_EDIT_BUSINESS_HOUR_REQUEST_SUCCESS =
  "ADD_VS_EDIT_BUSINESS_HOUR_REQUEST_SUCCESS";
export const ADD_VS_EDIT_BUSINESS_HOUR_REQUEST_ERROR =
  "ADD_VS_EDIT_BUSINESS_HOUR_REQUEST_ERROR";
export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_REQUEST_SUCCESS = "GET_LOCATION_REQUEST_SUCCESS";
export const GET_LOCATION_REQUEST_ERROR = "GET_LOCATION_REQUEST_ERROR";
export const SAVE_LOCATION_REQUEST = "SAVE_LOCATION_REQUEST";
export const SAVE_LOCATION_REQUEST_SUCCESS = "SAVE_LOCATION_REQUEST_SUCCESS";
export const SAVE_LOCATION_REQUEST_ERROR = "SAVE_LOCATION_REQUEST_ERROR";
export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_REQUEST_SUCCESS =
  "DELETE_LOCATION_REQUEST_SUCCESS";
export const DELETE_LOCATION_REQUEST_ERROR = "DELETE_LOCATION_REQUEST_ERROR";
export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";
export const IMAGE_LISTING_REQUEST = "IMAGE_LISTING_REQUEST";
export const IMAGE_LISTING_SUCCESS = "IMAGE_LISTING_SUCCESS";
export const IMAGE_LISTING_ERROR = "IMAGE_LISTING_ERROR";

export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_ERROR = "IMAGE_DELETE_ERROR";

export const BILLING_INFO_REQUEST = "BILLING_INFO_REQUEST";
export const BILLING_INFO_SUCCESS = "BILLING_INFO_SUCCESS";
export const BILLING_INFO_ERROR = "BILLING_INFO_ERROR";
export const SAVE_BILLING_INFO_REQUEST = "SAVE_BILLING_INFO_REQUEST";
export const SAVE_BILLING_INFO_SUCCESS = "SAVE_BILLING_INFO_SUCCESS";
export const SAVE_BILLING_INFO_ERROR = "SAVE_BILLING_INFO_ERROR";
export const INTEGRATION_INFO_REQUEST = "INTEGRATION_INFO_SUCCESS";
export const INTEGRATION_INFO_SUCCESS = "BILLING_INFO_SUCCESS";
export const INTEGRATION_INFO_ERROR = "INTEGRATION_INFO_ERROR";
export const SAVE_INTEGRATION_INFO_REQUEST = "SAVE_INTEGRATION_INFO_REQUEST";
export const SAVE_INTEGRATION_INFO_SUCCESS = "SAVE_INTEGRATION_INFO_SUCCESS";
export const SAVE_INTEGRATION_INFO_ERROR = "SAVE_INTEGRATION_INFO_ERROR";
export const CLEAR_DASHBOARD_DATA = "CLEAR_DASHBOARD_DATA";
export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_ERROR = "DELETE_BUSINESS_ERROR";
export const ADD_BUSINESS_REQUEST = "ADD_BUSINESS_REQUEST";
export const ADD_BUSINESS_SUCCESS = "ADD_BUSINESS_SUCCESS";
export const ADD_BUSINESS_ERROR = "ADD_BUSINESS_ERROR";
export const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_ERROR = "UPDATE_BUSINESS_ERROR";
export const ORDER_LISTING_REQUEST = "ORDER_LISTING_REQUEST";
export const ORDER_LISTING_SUCCESS = "ORDER_LISTING_SUCCESS";
export const ORDER_LISTING_ERROR = "ORDER_LISTING_ERROR";
export const LOAD_MORE_ORDER_LISTING_REQUEST =
  "LOAD_MORE_ORDER_LISTING_REQUEST";
export const LOAD_MORE_ORDER_LISTING_SUCCESS =
  "LOAD_MORE_ORDER_LISTING_SUCCESS";
export const LOAD_MORE_ORDER_LISTING_ERROR = "LOAD_MORE_ORDER_LISTING_ERROR";
export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_ERROR = "ORDER_DETAIL_ERROR";
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const ORDER_VIEW_REQUEST = "ORDER_VIEW_REQUEST";
export const ORDER_VIEW_SUCCESS = "ORDER_VIEW_SUCCESS";
export const ORDER_VIEW_ERROR = "ORDER_VIEW_ERROR";

export const ORDER_SETTING_REQUEST = "ORDER_SETTING_REQUEST";
export const ORDER_SETTING_SUCCESS = "ORDER_SETTING_SUCCESS";
export const ORDER_SETTING_ERROR = "ORDER_SETTING_ERROR";

export const INVENTORY_UPDATE_REQUEST = "INVENTORY_UPDATE_REQUEST";
export const INVENTORY_UPDATE_SUCCESS = "INVENTORY_UPDATE_SUCCESS";
export const INVENTORY_UPDATE_ERROR = "INVENTORY_UPDATE_ERROR";

export const UPDATE_BUSINESS_ID = "UPDATE_BUSINESS_ID";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_ERROR = "ORDER_UPDATE_ERROR";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_REQUEST_SUCCESS = "PASSWORD_RESET_REQUEST_SUCCESS";
export const PASSWORD_RESET_REQUEST_ERROR = "PASSWORD_RESET_REQUEST_ERROR";
export const PASSWORD_RESET_USER_REQUEST = "PASSWORD_RESET_USER_REQUEST";
export const PASSWORD_RESET_USER_REQUEST_SUCCESS = "PASSWORD_RESET_USER_REQUEST_SUCCESS";
export const PASSWORD_RESET_USER_REQUEST_ERROR = "PASSWORD_RESET_USER_REQUEST_ERROR";

export const USER_PASSWORD_UPDATE_REQUEST = "USER_PASSWORD_UPDATE_REQUEST";
export const USER_PASSWORD_UPDATE_REQUEST_SUCCESS = "USER_PASSWORD_UPDATE_REQUEST_SUCCESS";
export const USER_PASSWORD_UPDATE_REQUEST_ERROR = "USER_PASSWORD_UPDATE_REQUEST_ERROR";
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_REQUEST_SUCCESS = "USER_DELETE_REQUEST_SUCCESS";
export const USER_DELETE_REQUEST_ERROR = "USER_DELETE_REQUEST_ERROR";

export const MOVE_PRODUCT_IMAGES_REQUEST = "MOVE_PRODUCT_IMAGES_REQUEST";
export const MOVE_PRODUCT_IMAGES_REQUEST_SUCCESS = "MOVE_PRODUCT_IMAGES_REQUEST_SUCCESS";
export const MOVE_PRODUCT_IMAGES_REQUEST_ERROR = "MOVE_PRODUCT_IMAGES_REQUEST_ERROR";

export const USER_INVITATION_TOKEN_REQUEST = "USER_INVITATION_TOKEN_REQUEST";
export const USER_INVITATION_TOKEN_REQUEST_SUCCESS = "USER_INVITATION_TOKEN_REQUEST_SUCCESS";
export const USER_INVITATION_TOKEN_REQUEST_ERROR = "USER_INVITATION_TOKEN_REQUEST_ERROR";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_REQUEST_SUCCESS = "EMPLOYEE_UPDATE_REQUEST_SUCCESS";
export const EMPLOYEE_UPDATE_REQUEST_ERROR = "EMPLOYEE_UPDATE_REQUEST_ERROR";