const APP_STRING = {
  BUSINESS_NAME: "Please enter your business name.",
  BUSINESS_TYPE: "Please choose business type.",
  ENTER_FIRSTNAME: "Please enter your first name.",
  ENTER_LASTNAME: "Please enter your last name.",
  ENTER_EMAIL: "Please enter your email.",
  TERMAND_POLICY: "Please accept Terms of Use.",
  ENTER_PASSWORD: "Please enter your password.",
  ENTER_VALID_EMAIL: "Please enter valid email.",
  ENTER_SIX_DIGIT_PASSWORD: "Password contain at least 6 digits.",
  ENTER_VALID_PASSWORD:
    "Password enter password which contain at least 8 characters, 1 uppercase , 1 lowercase and 1 digit.",
  PASSWORD_MITCHMATCH: "Your password not match with confirm password.",
  ENTER_PRODUCT_NAME: "Please enter name of items.",
  ENTER_BRAND_NAME: "Please enter brand name.",
  SELECT_CATEGORY: "Please select category.",
  SELECT_AVAILABILITY: "Please choose availability of item.",
  DEAL_PRICE: "Please enter deal price.",
  DEAL_QTY: "Please enter deal quanity.",
  SELECT_BUSINESS: "Please select any business.",
  EMP_BUSINESS: "Please select any permission.",
  PRICE: "Please enter price.",
  PRODUCT_IMAGE: "Please select product image",
  UNIT1QTY: "Please enter unit 1 quanity.",
  UNIT1TYPE: "Please select unit 1 type.",
  UNIT2QTY: "Please enter unit 2 quanity.",
  UNIT2TYPE: "Please select unit 2 type.",
  ONE: "1",
  ZERO: "0",
  CATALOG: "Catalog",
  ENTER_FULL_NAME: "Please enter full name",
  ENTER_CARD_NUMBER: "Please enter card number",
  ENTER_VALID_CARD_NUMBER: "Please enter valid card number",
  ENTER_ZIP: "Please enter zip code",
  ENTER_STREET: "Please enter street name",
  ENTER_CITY: "Please enter city",
  ENTER_STATE: "Please enter state",
  ENTER_EXPIRY_MONTH: "Please enter expiry month",
  ENTER_EXPIRY_YEAR: "Please enter expiry year",
  ENTER_EXPIRY_CVV: "Please enter CVV",
};
export default APP_STRING;
